[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "lipid-pathway-integrator"
authors = [
    { name = "Dylan Ross", email = "dylan.ross@pnnl.gov" }
]
description = "Unifies lipid ontology-aware representation and pathway-based multi-omics integration in a single framework"
readme = "README.md"
dynamic = ["version"]
requires-python = ">=3.14"
dependencies = [
    "PyYAML>=6.0.3",
    "networkx>=3.6",
    "requests>=2.32.5",
    "matplotlib>=3.10.7",
    "polars>=1.38.1",
    "jupyter>=1.1.1",
    "scipy>=1.18.0",
    "lipidimea>=2.0.1",
]

[project.urls]
Repository = "https://github.com/pnnl-compbio/lipid_pathway_integrator"
Documentation = "https://lipi.readthedocs.io"
Issues = "https://github.com/pnnl-compbio/lipid_pathway_integrator/issues"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["lipi"]

[tool.setuptools.dynamic]
version = {attr = "lipi.__version__"}

[tool.setuptools.package-data]
lipid_pathway_integrator = ["_resources/*"]

[project.optional-dependencies]
docs = [
    "sphinx>=7.0",
    "sphinx-rtd-theme>=2.0",
    "numpydoc>=1.5",
    "sphinx-autodoc-typehints>=1.24",
    "sphinx-autobuild>=2024.0",
]
